name: AWS_deploy

on:
  push:
    branches: [ master ]
jobs:
  Build: 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Create .env file
        run: echo 'PORT=${{ secrets.PORT }}' > .env

      - name: Run Build
        run:  sudo docker-compose up -d
          
