# This is a basic workflow to help you get started with Actions

name: aws_deploy

on:
  push:
    branches: [ develop ]
jobs:
  Build: 
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master

      - name: Create .env file
        run: echo 'PORT=${{ secrets.PORT }}' > .env

      - name: Run Build
        run:  docker-compose -d
          
